services:
  shortener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shortener
    ports:
      - "8080:${SERVER_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - appnet

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 3s
      timeout: 5s
      retries: 1
    networks:
      - appnet

volumes:
  postgres_data:

networks:
  appnet:
    driver: bridge