name: Build and Deploy Docker App

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}
      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create a new tag
        run: |
          git tag -a ${{ github.event.inputs.tag }} -m "Tag created via GitHub Actions"
          git push origin ${{ github.event.inputs.tag }}    
      - name: Check if tag exists
        run: |
          git fetch --all --tags
          if ! git tag | grep -q "^${{ github.event.inputs.tag }}$"; then
            echo "error: Tag '${{ github.event.inputs.tag }}' not found"
            exit 1
          fi    
      
      - name: Set up Docker
        run: |
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Build Docker image
        run: |
          docker build -t url-shortener .

      - name: Run Docker container
        run: |
          docker run -d -p 8082:8082 --name url-shortener url-shortener

      - name: Clean up Docker
        run: |
          docker stop url-shortener
          docker rm url-shortener
