name: Build and Deploy Docker App

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }} 

      - name: Build Docker image
        run: |
          docker build -t url-shortener .

      - name: Run Docker container
        run: |
          docker run -d -p 8082:8082 --name url-shortener url-shortener
